### ISSUE TITLE
Status "gelöscht"

### ISSUE THREAD

**Issue by rpw61** [ghwalin/exam_frontend#12]
Der Status "gelöscht" impliziert, dass der Eintrag nicht mehr sichtbar ist (in der Übersicht des Owners).
Eine Bezeichnung wie "sistiert" oder "abgemeldet" würde aus meiner Sicht mehr Klarheit geben.

**Comment by graphics80** [comment]
Im Status "gelöscht" sollte es visuell ersichtlich sein, zum Beispiel indem der Text durchgestrichen ist oder der Hintergrund rot ist.

**Comment by ghwalin** [comment]
related #3

**Comment by ghwalin** [comment]
Der Status "gelöscht" ist durch ein rotes Symbol "Papierkorb" gekennzeichnet.
Inzwischen ist der Fehler korrigiert, dass auch Nachprüfungen mit dem Status "gelöscht" in der Maske für die Prüfungsaufsicht gezeigt werden. (Siehe #3)
