### ISSUE TITLE
Aufgebot trotz Status "gelöscht" zugestellt.

### ISSUE THREAD

**Issue by rpw61** [ghwalin/exam_frontend#13]
Die Lernende Lutz hat den Status "gelöscht". Trotzdem wurde ihr ein Aufgebot zugestellt.

Ich habe in der Ansicht "Aufsicht" das Häckchen für alle Kandidaten angewählt. Da erscheint aber auch Frau Lutz mit Status "gelöscht"  (das habe ich abererst im Nachgang festgestellt). Die Aktion [Aufgebot senden] führt dazu, dass eben dieses Aufgebot trotzdem gesendet wurde.

**Comment by ghwalin** [comment]
relates to #3

**Comment by ghwalin** [comment]
Nachprüfungen mit Status "gelöscht" werden in der Aufsichtsseite nicht mehr angezeigt und können daher nicht mehr ausgewählt werden.
Das Verhalten des Emailversands ist korrekt.
