### ISSUE TITLE
Mehrfaches Aufgebot

### ISSUE THREAD

**Issue by rpw61** [ghwalin/exam_frontend#14]
Die Lernende Taiter ist für den 10.6 3 Mal erfasst (3 Nachprüfungen). Sie hat nun auch 3 Mails erhalten. 
Es gibt sicher die Begründung, dass die/der Lernende so weiss, dass mehrere Nachprüfungen anstehen. Man könnte das evtl. dann aber auch in einer Mail abhandeln und die Zahl der anstehenden Prüfungen bei >1 mitteilen.

**Comment by ghwalin** [comment]
Das Problem tritt nur in den seltenen Fall auf, dass der gleiche Lernende von der gleichen Lehrperson zu mehreren Nachprüfungen aufgeboten wird. Sobald es unterschiedliche Lehrpersonen sind, ändert sich der Verteiler der Emails und kann somit nicht in einer Email abgedeckt werden.

Wird nicht weiter verfolgt.
